config/routes.rb
Rails.application.routes.draw do
  devise_for :users


  resources :users, only: [:show, :index]
  resources :topics, only: [:index, :show, :new, :create] do
    resources :answers, only: [:create]
  end
  resources :levels, only: [:show, :create]

  root 'static_pages#home'

  get 'about' => 'static_pages#about', as: 'about'

  get 'play/(:id)' => 'levels#play', as: 'play'
  get 'editor' => 'levels#editor', as: 'editor'

  get 'account' => 'users#account', as: 'account'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :topic
  belongs_to :author, class_name: 'User'

  validates :topic_id, presence: true
  validates :author_id, presence: true
  validates :content, presence: true, length: { maximum: 250 }
end

app/models/level.rb
class Level < ActiveRecord::Base
  belongs_to :creator, class_name: "User"

  has_many :solving_informations, foreign_key: :solved_level_id
  has_many :solvers, through: :solving_informations
end

app/models/solving_information.rb
class SolvingInformation < ActiveRecord::Base
  belongs_to :solver, class_name: "User"
  belongs_to :solved_level, class_name: "Level"
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  before_create :set_counter
  belongs_to :author, class_name: 'User'
  has_many :answers

  validates :author_id, presence: true
  validates :title, presence: true, length: { maximum: 80 }
  validates :content, presence: true, length: { maximum: 1200 }

  def creator
    return author.username if author
    'User deleted.'
  end

  private

  def set_counter
    self.counter = 0
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true, length: { maximum: 40 }

  has_many :topics, foreign_key: :author_id
  has_many :answers, foreign_key: :author_id
  has_many :levels, foreign_key: :creator_id

  has_many :solving_informations, foreign_key: :solver_id
  has_many :solved_levels, through: :solving_informations
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  expose(:answer) { current_user.answers.build(answer_params) }

  def create
    if answer.save
      flash[:info] = "success"
    else
      flash[:warning] = "failure"
    end
      redirect_to :back
  end

  private

  def answer_params
    params.require(:answer).permit(:content, :topic_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:account_update) << :username
  end

  def after_sign_in_path_for(resource)
    account_path
  end

  def after_sign_up_path_for(resource)
    account_path # Or :prefix_to_your_route
  end

  private

  def require_login(path = root_path)
    return true if user_signed_in?
    flash[:danger] = 'You cannot do this! First sign in or sign up'
    redirect_to path
  end
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  before_filter(only: [:create]) { require_login(play_path) }
  respond_to :js, :html
  expose(:level)     { Level.find_by(id: params[:id]) }
  expose(:new_level) { Level.new(logix_params) }

  def play
    if level
      b = level.blocks
      h = level.homes
      m = level.map
      respond_to do |format|
        format.js   { render 'play.js',   locals: { blocks: b, homes: h, map: m } }
        format.html { render 'play.html', locals: { blocks: b, homes: h, map: m } }
      end
    else
      render 'play'
    end
  end

  def create
    new_level.level_type = 'User made'
    new_level.creator    = current_user
    if new_level.save
      flash[:info] = "success"
    else
      flash[:warning] = "danger"
    end
    render nothing: true
  end

  def logix_params
    { blocks: params[:hash_blocks],
      homes: params[:hash_homes],
      map: params[:map_arr] }
  end
end

app/controllers/solving_informations_controller.rb
class SolvingInformationsController < ApplicationController
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter(only: [:new, :create]) { require_login(topics_path) }
  expose(:new_topic) { Topic.new }
  expose(:topic)     { Topic.includes(answers: [:author]).find(params[:id]) }
  expose(:topics)    { Topic.includes(:answers).order(created_at: :desc) }
  expose(:answer)    { Answer.new }

  def show
    topic.update(counter: topic.counter+1)
  end

  def create
    @topic = current_user.topics.build(topic_params)
    if @topic.save
      flash[:info] = 'Topic created!'
      redirect_to topic_path(@topic)
    else
      render 'new'
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:title, :content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter(only: [:account]) { require_login(root_path) }
  expose(:users)
  expose(:user)

  def show
  end

  def index
  end

  def account
  end
end

app/helpers/levels_helper.rb
module LevelsHelper
  def button_triangles(color)
    content_tag :div do
      content_tag(:div, "", class: ["triangle-tl", "#{color[0]}"]) +
      content_tag(:div, "", class: ["triangle-bl", "#{color[0]}"]) +
      content_tag(:div, "", class: ["triangle-tr", "#{color[0]}"]) +
      content_tag(:div, "", class: ["triangle-br", "#{color[0]}"]) +
      color
    end
  end
end

app/helpers/solving_informations_helper.rb
module SolvingInformationsHelper
end

app/views/answers/_answer.html.haml
#author
  %p
    Answer by:
    = link_to "#{answer.author.username}", answer.author
#content
  = answer.content

app/views/answers/_new_answer.html.haml
#new-response
  = simple_form_for answer, url: topic_answers_path(topic), method: :post do |f|
    = f.error_notification
    .form-inputs
      = f.input :content
      = f.hidden_field :topic_id, value: topic.id
    .form-actions
      = f.button :submit, "Send"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Logix
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body

    - flash.each do |message_type, message|
      %div{:class => "alert alert-#{message_type}"}= message
    #main
      = render 'shared/header'
      #content-wrapper.clearfix
        = yield

app/views/levels/editor.html.haml
#game-wrapper
  #container.wrapper
    %canvas#canvas{width: "390", height: "390"}
#editor-functions
  #new-level.btn.btn-default
    = "create new level"
  #walls
    = button_triangles("wall")
    = button_triangles("square")
  #blocks
    = button_triangles("red")
    = button_triangles("blue")
    = button_triangles("green")
    = button_triangles("violet")
    = button_triangles("teal")
    = button_triangles("yellow")
  #homes
    = button_triangles("red")
    = button_triangles("blue")
    = button_triangles("green")
    = button_triangles("violet")
    = button_triangles("teal")
    = button_triangles("yellow")

:javascript
  new_level()
  editor()

app/views/levels/level.js.haml
window.heh("#{blocks}","#{homes}","#{map}")

app/views/levels/new.js.haml
editor()

app/views/levels/play.html.haml
#game-wrapper
  #container.wrapper
    %canvas#canvas{width: "390", height: "390"}
#functions-wrapper
  .btn-group
    #easier.btn.btn-default
      Easier difficulty
    #harder.btn.btn-default
      Harder difficulty
    #typebutton.panel.panel-default
      Novice
  .btn-group
    #prevlvl.btn.btn-default
      Previous level
    #nextlvl.btn.btn-default
      Next level
    #levelbutton.panel.panel-default.btn-default
      Level 1
  #solve.panel.panel-default.center-block.btn-default.btn{ style: "width: 200px"}
    Solve!
  #counter.panel.panel-default.center-block{ style: "width: 200px"}
    Moves:

  #directions.btn-group{ style: "margin-top: 40px" }
    %span#left.btn.btn-default
      Left
    .btn-group.btn-group-vertical{ style: "margin-top: -17px" }
      %span#up.btn.btn-default
        Up
      %span#down.btn.btn-default
        Down
    %span#right.btn.btn-default
      Right

- if defined?(blocks)
  :javascript
    heh('#{blocks}','#{homes}','#{map}')
- else
  :javascript
    new_level()

app/views/levels/play.js.haml
window.heh("#{blocks}","#{homes}","#{map}")

app/views/shared/_header.html.haml
#header-wrapper
  %ul.nav.nav-tabs
    %li
      = link_to "Logix", root_path, method: :get
    %li
      = link_to "PLAY", play_path, method: :get
    %li
      = link_to "editor", editor_path, method: :get
    %li
      = link_to "About", about_path, method: :get
    %li
      = link_to "users", users_path, method: :get
    %li
      = link_to "Forum", topics_path, method: :get
    - if user_signed_in?
      %li
        = link_to "Account", account_path, method: :get
      %li
        = link_to "New topic", new_topic_path, method: :get
      %li
        = link_to "logout", destroy_user_session_path, method: :delete
    -else
      %li
        = link_to "Log in", new_user_session_path, method: :get
      %li
        = link_to "Register", new_user_registration_path, method: :get

app/views/static_pages/about.html.haml
#title
  %p
    Logix
#description
  %p
    Logix is a logic game. Have fun!
  %p
    Just press play button, choose the level you with next/prev buttons and click the button with level name to load it. You can move even with arrow keys on your keyboard. Have fun!
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec augue purus, lacinia at laoreet et, mollis at turpis. Maecenas blandit risus mi, et lobortis nunc condimentum et. Quisque non libero a erat cursus vulputate. Morbi dictum posuere ante. Nulla dapibus id erat sed posuere. Aenean ex libero, viverra ac hendrerit sed, rhoncus eget enim. Vestibulum at tellus accumsan, mollis tellus id, vehicula nisl. Donec nec lectus leo. Nullam hendrerit ultrices lorem, id scelerisque dolor eleifend at. Nam in euismod dolor, vel luctus erat.

app/views/static_pages/home.html.haml
#content-left
  #title
    %p
      Logix
  #description
    %p
      Just press play button, choose the level you want with next/prev buttons and click the button with level name to load it. You can move with buttons or with arrow keys on your keyboard. Have fun!
#content-right
  #gallery
    #screenshot.clearfix
      #previous
        #triangle-left
      = image_tag("ss1.png",id: "image1",style: "opacity:1;",class: "clearfix")
      = image_tag("ss2.png",id: "image2",style: "opacity:0;",class: "clearfix")
      = image_tag("ss3.png",id: "image3",style: "opacity:0;",class: "clearfix")
      #next
        #triangle-right

app/views/static_pages/play.html.haml
#game-wrapper
  #container.wrapper
    %canvas#canvas{width: "390", height: "390"}
#functions-wrapper
  #choose-time
    #chooselevel
      #new-level
        %p
          Previous level
      #levels
        #prevlvl
          %p
            Previous level
        #nextlvl
          %p
            Next level
      #levelbutton
        %p
          Level 1
  #play-time
    #arrows
      #counter.dirbutton
        %p
          Moves:
        %span
      %button#up.dirbutton
        Up
      #directions
        %button#left.dirbutton
          Left
        %button#right.dirbutton
          Right
      %button#down.dirbutton
        Down
  #play-time
    #blocks
      = button_triangles("red")
      = button_triangles("blue")
      = button_triangles("green")
      = button_triangles("violet")
      = button_triangles("teal")
      = button_triangles("yellow")
    #homes
      = button_triangles("red")
      = button_triangles("blue")
      = button_triangles("green")
      = button_triangles("violet")
      = button_triangles("teal")
      = button_triangles("yellow")

app/views/topics/index.html.haml
#topic-header
  Latest topics:
%table.table.table-hover
  %tr
    %th
      Title
    %th
      Views
    %th
      Posts
    %th
      Activity
  - topics.each do |t|
    %tr
      %td
        = link_to t.title, topic_path(t)
      %td.details
        = t.counter
      %td.details
        = t.answers.length
      %td.when
        = "#{time_ago_in_words(t.created_at)} ago"

app/views/topics/new.html.haml
#topic-header
  Create new topic:
#new-topic
  = simple_form_for( new_topic, html: { class: 'form-horizontal' } ) do |f|
    = f.error_notification
    .form-inputs
      = f.input :title, required: true
      = f.input :content, required: true
    .form-actions
      = f.button :submit

app/views/topics/show.html.haml
#topic-display
  #topic-header
    = topic.title
  #info.clearfix
    #author
      %p
        Topic by:
        = link_to "#{topic.creator}", topic.author
    #when
      %p
        = "Last post #{time_ago_in_words(topic.created_at)} ago"
  #content
    = topic.content
#answers
  #topic-display
    = render topic.answers

#content
  = render 'answers/new_answer'

app/views/users/account.html.haml
%h1
  Manage your account:
%h2
  = link_to "Your profile", current_user
%h3
  = link_to 'Update your account', edit_user_registration_path
%h2
  My levels:
  %h4.lists
    - current_user.levels.order("created_at").each do |l|
      = link_to "Level #{l.id}", play_path(l)

app/views/users/index.html.haml
%h1
  Top users:
#users
  - users.each_with_index do |u, index|
    #user
      %h3
        = link_to "#{index+1} #{u.username}",  u

app/views/users/show.html.haml
#user
  %h1
    Profile of user:
  %h2
    = user.username
  %h3
    = user.email
  %h3
    Latest topics:
    #user-topics.lists
      %h4
        - user.topics.each do |t|
          = link_to "#{t.title}", t
  %h3
    Latest answers:
    #user-answers.lists
      %h4
        - user.answers.each do |a|
          = link_to "#{a.topic.title}", a.topic
  %h3
    My levels:
    #user-levels.lists
      %h4
        - user.levels.order("created_at").each do |l|
          = link_to "Level #{l.id}", play_path(l)